server:
  port: 8010

spring:
  application:
    name: api-order-add
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 0.1


eureka:
  client:
    service-url:
      defaultZone: http://root:siki@localhost:9001/eureka
feign:
  hystrix:
    enabled: true


