server:
  port: 9002

spring:
  application:
    name: api-user-login
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1

eureka:
  client:
    service-url:
      defaultZone: http://root:siki@localhost:9001/eureka

feign:
  hystrix:
    enabled: true

