server:
  port: 9002

spring:
  application:
    name: api-user-login

eureka:
  client:
    service-url:
      defaultZone: http://root:siki@localhost:9001/eureka

feign:
  hystrix:
    enabled: true

