server:
  port: 8014

spring:
  application:
    name: shopcart-del
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://47.120.13.50:3306/kzmall?useSSL=false


eureka:
  client:
    service-url:
      defaultZone: http://root:siki@localhost:9001/eureka


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.gyb.entity
